
// This is an autogenerated file from Firebase Studio.
import NextAuth, { type NextAuthOptions } from 'next-auth';
import CredentialsProvider from 'next-auth/providers/credentials';

// Mock user database (replace with actual database logic in a real app)
// This will now primarily serve as a fallback or for direct NextAuth credential logins if not pre-validated.
const users = [
  { id: '1', name: 'Test User', email: 'test@example.com', password: 'password123' },
  { id: '2', name: 'Jane Doe', email: 'jane@example.com', password: 'password' },
];

export const authOptions: NextAuthOptions = {
  providers: [
    CredentialsProvider({
      name: 'Credentials',
      credentials: {
        email: { label: 'Email', type: 'email', placeholder: 'name@example.com' },
        password: { label: 'Password', type: 'password' }, // Still here for direct credential flow
        // For pre-validated flow from your backend
        name: { label: 'Name', type: 'text' },
        id: { label: 'User ID', type: 'text' },
        isPreValidated: { label: 'Is Pre-Validated', type: 'hidden' } // string 'true' or undefined
      },
      async authorize(credentials) {
        // Handle pre-validated flow
        if (credentials?.isPreValidated === 'true' && credentials.email && credentials.id) {
          // If 'isPreValidated' is true, we trust the details passed from our frontend
          // which should have received them from a successful call to the user's custom backend.
          return { 
            id: credentials.id, 
            name: credentials.name || credentials.email, // Use name if provided, else email
            email: credentials.email 
          };
        }

        // Original password validation logic (fallback or for direct NextAuth login)
        if (!credentials?.email || !credentials?.password) {
          return null; // Not enough info for password check
        }
        const user = users.find((u) => u.email === credentials.email);

        // IMPORTANT: In a real application, you MUST hash and compare passwords securely.
        // Storing plain text passwords is a major security vulnerability.
        // This part is for the fallback scenario.
        if (user && user.password === credentials.password) {
          return { id: user.id, name: user.name, email: user.email };
        }
        
        // If you return null then an error will be displayed advising the user to check their details.
        return null;
      },
    }),
  ],
  session: {
    strategy: 'jwt',
  },
  pages: {
    signIn: '/login', // Redirect users to this page for sign in
    // error: '/login', // Redirect users to this page on error (optional)
  },
  callbacks: {
    async jwt({ token, user }) {
      // Persist the user id (and potentially name) to the token right after signin
      if (user) {
        token.id = user.id;
        // token.name = user.name; // name is usually part of the default token if returned by authorize
      }
      return token;
    },
    async session({ session, token }) {
      // Send properties to the client, like user id from the token.
      if (session.user) {
        session.user.id = token.id as string;
        // session.user.name = token.name as string; // name is usually part of default session.user
      }
      return session;
    },
  },
  secret: process.env.NEXTAUTH_SECRET,
};

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
