// This is an autogenerated file from Firebase Studio.
import type { DefaultSession, User as DefaultUser } from 'next-auth';
import type { JWT as DefaultJWT } from 'next-auth/jwt';

declare module 'next-auth' {
  interface Session {
    user: {
      id?: string | null;
    } & DefaultSession['user'];
  }

  interface User extends DefaultUser {
    id?: string;
  }
}

declare module 'next-auth/jwt' {
  interface JWT extends DefaultJWT {
    id?: string;
  }
}
