// This is an autogenerated file from Firebase Studio.
'use client';

import type { Session } from 'next-auth';
import { SessionProvider } from 'next-auth/react';
import type { ReactNode } from 'react';

interface NextAuthProviderProps {
  children: ReactNode;
  session?: Session; // Optional: for server-side session pre-population
}

export default function NextAuthProvider({ children, session }: NextAuthProviderProps) {
  return <SessionProvider session={session}>{children}</SessionProvider>;
}
